# Generated by Django 4.2.30 on 2026-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
